### ISSUE TITLE
Support semi-required parameters

### ISSUE THREAD

**Issue by Silind** [Silind/twitter-api-client#18]
**Is your feature request related to a problem? Please describe.**  
For multiple endpoints, there is a constraint that either `user_id` or `screen_name` should be provided.
An example can be found in [this bug report](https://github.com/Silind/twitter-api-client/issues/11).

On the Twitter Documentation, both `user_id` and `screen_name` is flagged as `required`, where in fact, only one of them is required.
This is also stated in the description.

I will call these types of parameters *semi-required* in respect to another parameter.

**Describe the solution you'd like**  
Back in a very early version, I introduced a type `UserIdOrScreenName` that was able to make exactly this inference.
[See the implementation here](https://github.com/Silind/twitter-api-client/blob/7fd6cc9ab6cfffafbae3084b4cf65fa283d89a99/src/interfaces/GenericTypes.ts#L1-L4)
This type got discarded due to the introduction of the generators.

I suggest that we reintroduce this type and introduce a new syntax in the `twitter-api-spec.yml` file, that indicates semi-required fields.

A suggestion could be the following:

```yml
parameters:
  - name: user_id
    description: ....
    required: !screen_name # <- Conditional requirement
    type: number
  - name: screen_name
    description: ....
    required: !user_id # <- Conditional requirement
    type: string
```

**Describe alternatives you've considered**  
I think the above suggestion would be feasible, however, we could also implement solutions inspired by big projects, to make the syntax more familiar.

Here is a couple of examples of conditionals in YAML specifications:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html

**Additional context**  
Let's discuss a good solution in this issue 👇

**Comment by iliran11** [comment]
Hi,
I think the suggested syntax is generic and flexible - gives you a room for combination.  But can produce complex interfaces - and that might cost in implementation time.

I have another suggestion for something less generic, and therefore it also conveys what is the specific problem it is going to solve:

```
          parameters:
            - name: force_login
              description: Forces the user to enter their credentials to ensure the correct users account is authorized.
              required: false
              type: boolean
            - name: x
              description: Some description
              required: false
              type: string
          one-of-parameters: 
            - identification-options: 
              - name: user_id
                description: 'xxx'
                type: number
              - name: screen_name
                description: yyy
                type: string
```

**Comment by iliran11** [comment]
Hi,
I think the suggested syntax is generic and flexible - gives you a room for combinations.  But can also produce complex interfaces - and that might cost in implementation time.

I have another less-generic and less-complex suggestion.
The assumption is a field can appear only once in the `one-of-parameters` section:

```
          parameters:
            - name: force_login
              description: Forces the user to enter their credentials to ensure the correct users account is authorized.
              required: false
              type: boolean
            - name: x
              description: Some description
              required: false
              type: string
          one-of-parameters: 
            - identification-options: 
              - name: user_id
                description: 'xxx'
                type: number
              - name: screen_name
                description: yyy
                type: string
```
